### PR TITLE
Transport of packets between the pool of workers

### PR DESCRIPTION
**Pull request by JC5LZiy3HVfV5ux**

### CODE REVIEW

**Comment by JC5LZiy3HVfV5ux** [comment]
@peakedshout Hello! After your message, I conducted some tests and realized that my approach was not entirely correct. This pull request should improve the server's stability. I thought you might be able to share your opinion on how successful this solution is. Thanks again for encouraging me to explore the issue!

> if the client generates a large amount of data in a short period of time, then this will cause unpredictable overhead.

**Comment by peakedshout** [comment]
...? I don't know how you came to this conclusion, but at least, I looked at some of your source code and found that the problem wasn't solved. If you're just talking about the work pool, there's nothing wrong with the general scenario, but I'm not going to judge your actual scenario. In general, for network forwarding, only the number of concurrent connections is limited, but not the number of concurrent packets. If it were just a pool of work, I can't think of a place where this project could be used, because the golang runtime has its own limitations. Generally, in scenarios with work pools, some high concurrency occurs and an immeasurable number occurs, which will cause the global concurrency to be too high and affect the overall operation. In my opinion, socks does not have such a scenario.

**Comment by JC5LZiy3HVfV5ux** [comment]
@peakedshout Thanks for the answer! I based my work on other Go packages that use the UDP protocol. I'll keep looking for solutions.

**Comment by peakedshout** [comment]
In fact, the problem is easy to solve, which is to let the UDP socket accept the information itself and send the data out, and let the pressure be placed on the kernel layer, which is correct. Rather than sending data asynchronously and uncontrollably. For example, if you have a large amount of data waiting to be sent, it will cause the memory to be bloated and lead to a bottleneck in the final transmission and reception rate. It's also the easiest. Again, because you're creating slices in a loop, in a high-concurrency situation, this causes the memory to go up very quickly, and the data isn't delivered to the kernel very quickly. My personal design style is more obsessed with memory and concurrency, which is just my personal opinion. And, considering the actual scenario, the 6xxxx size of data on the LAN and the 1500 size packets in the public network, I think you should have thought of another serious problem.

**Comment by JC5LZiy3HVfV5ux** [comment]
I will try to figure it out. Any articles or code examples in Go would be extremely helpful, but please don't feel obligated to spend time on this.

**Comment by peakedshout** [comment]
I would like to share my latest implementation, but my implementation is embedded in other projects (because I think it is just a simple tool library), and this project is still private and will not be open until it is sorted out and evaluated. Access, it may take a while before this project will be open; currently my personal focus is on the scaffolding of the 2D engine, and I am waiting for the progress of my collaborators on the network project.

**Comment by JC5LZiy3HVfV5ux** [comment]
@peakedshout Hello! Does this draft (the latest commit) implement your idea? 

If I'm bothering you, please let me know. I will stop disturbing you.

**Comment by peakedshout** [comment]
emmm？Where is the latest code submission? I checked the master branch and it seems that there are no changes?
But there is good news. I am currently writing the documents to open the tool library. Here is my socks implementation, which should be completed in the next two days (mainly some documentation, for someone like me who writes code and often neglects to write documents) For humans, this is too painful)

**Comment by JC5LZiy3HVfV5ux** [comment]
No, the branch is feature/datagram_queue, which this pull request is related to. I will be happy to review your package; please let me know when you are done.

**Comment by peakedshout** [comment]
Hey, I looked at your udpAssociate method and it seems that there is no abnormal problem.
Although this is somewhat different from my latest implementation, because there are ambiguities in the specification document, I think there will be nothing unusual about this implementation. The most important thing is that it can serve the purpose, right? But I think you should understand that instead of doing too much caching and concurrency at the application layer, it is better to rely on the kernel layer to actually solve the traffic pressure.

**Comment by JC5LZiy3HVfV5ux** [comment]
I am new to projects like this and don’t know much. But thanks to you, I am slowly figuring things out. Thank you!

**Comment by peakedshout** [comment]
Hey, you can look at this https: //github.com/peakedshout/go-pandorasbox/tree/master/xnet/proxy/socks .
This is my socks library implementation, and it comes with some simple documentation. I hope it can be helpful to you.

**Comment by JC5LZiy3HVfV5ux** [comment]
Thank you! I will explore the functionality of the packages that interest me. I must say that at first glance the code does not seem intuitive and takes some time to understand. This is not necessarily a negative aspect and does not make the package less valuable. However, one of my goals is to prioritize simplicity and intuitiveness.

**Comment by peakedshout** [comment]
This is normal. In the design of this version, I took into account the maximum implementation of the socks protocol and adopted a large number of callback designs, which will make it easier for the caller to intervene in specific behaviors. In my opinion, the socks protocol is not a simple pipeline work. It has a high degree of freedom in customization (such as encryption after a successful handshake, which will require changes to the original net.Conn), in the form of callbacks. , will make this behavior easier.
In fact, users probably won't just use native SOCKS (e.g. on TLS, WS, with custom encryption, etc.), they just want a protocol carrier, and I expect to support that.
Similarly, if the user doesn't know what these are, then using the default setting will get the original protocol (just leave it alone).
This is my philosophy for designing this socks library, and if you have any questions during the review process, feel free to let me know, and I'm welcome to debate and corrections.

**Pull request closed without merging**
